---
title: "Summary figures"
author: "Julianna Renzi"
date: "3/16/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: lumen
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse) # data manipulation
require(here) # for relative paths
require(RColorBrewer) # for colors
```

# Make a plot of publications through time

Bring in the data and count up publications by year

```{r}
# bring in the data
time <- read_csv(here("data", "Corallivore_year_exptype.csv"))

time_sum <- time %>% 
  group_by(Year, Exp_type) %>% 
  summarize(Publications = n()) # get the count of publications per year

# duration of the graph we want
min_yr <- 1990
max_yr <- 2020

# create a dataframe of all possible values to join
all_years <- data.frame(Year = c(seq(min_yr, max_yr, by = 1),
                                seq(min_yr, max_yr, by = 1),
                                seq(min_yr, max_yr, by = 1)),
                        Exp_type = c(rep("Experimental", times = max_yr-min_yr+1),
                                     rep("Observational", times = max_yr-min_yr+1),
                                     rep("Both", times = max_yr-min_yr+1))) # create a df to join so that every year is accounted for (=0 if there are no publications)

time_full <- all_years %>% 
  full_join(time_sum, by = c("Year", "Exp_type")) %>% # join the two dataframes so there's a line for every year
  mutate(Publications = replace_na(Publications, 0)) # replace the NA's for 0 in the years where nothing was published

  
```


Plot the results

```{r}

time_full %>% 
  ggplot(aes(x = Year, y = Publications, fill = fct_reorder(Exp_type, desc(Exp_type)))) + # fct_reorder() so both is the last in the legend (makes the most sense)
  geom_bar(stat = "identity") +
  ylab("Number of studies") +
  geom_hline(yintercept = 0) + # create an x-axis that is distinct
  theme_minimal()  +
  scale_fill_manual(name = "", # no legend title 
                    values = rev(brewer.pal(n = 3, name = "YlOrBr"))) +
  scale_x_continuous(breaks = seq(1990, 2020, by = 2)) + # create a higher resolution on the x-axis
  theme(text = element_text(size = 15), legend.position = "top",
        axis.text.x = element_text(angle = 90, hjust = 1), # rotate axis labels
        axis.title.x = element_text(vjust = -1), # add padding fo titles (also need to adjust the margins)
        axis.title.y = element_text(vjust = 3),
        plot.margin = unit(c(5.5, 5.5, 10, 10), "points")) 
```

